<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIMEN" ignored="0" name="Test" tests="11" failures="1" timestamp="04 Apr 2018 21:00:35 GMT" time="21.338" errors="0">
  <testcase name="testCase" time="0.01" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.0" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.002" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.002" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.001" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="20.332" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:174)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
</testsuite> <!-- Test -->
